# Web image template. Copy to app/web/Dockerfile and replace APP_ values.
FROM docker.io/library/nginx:1.27-alpine

ARG ASSET_REV=dev
ARG APP_BUILD_COMMIT=
ARG APP_BUILD_DATE=

LABEL org.opencontainers.image.source="https://github.com/owner/myapp"
LABEL org.opencontainers.image.title="MyApp web"

COPY app/web/nginx.conf /etc/nginx/conf.d/default.conf
COPY app/web/index.html /usr/share/nginx/html/index.html
COPY app/web/css/ /usr/share/nginx/html/css/
COPY app/web/js/ /usr/share/nginx/html/js/

# Shared framework modules (vendored common/).
COPY common/web/js/ /usr/share/nginx/html/common/js/
COPY common/web/css/ /usr/share/nginx/html/common/css/

RUN sed -i "s#__ASSET_REV__#${ASSET_REV}#g" /usr/share/nginx/html/index.html
RUN sed -i "s#__BUILD_COMMIT__#${APP_BUILD_COMMIT}#g; s#__BUILD_DATE__#${APP_BUILD_DATE}#g" \
    /usr/share/nginx/html/index.html

EXPOSE 80
